In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import math

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
documents = ['dog chase cat dog','cat chase cat','car chase tv','dog watch dog tv','dog car sit car']
N=len(documents)
print(N)

5


In [12]:
 doc_counts={}
for doc in documents:
    for term in (doc.split()):
        if term not in doc_counts:
            doc_counts[term]=1
        else:
            doc_counts[term]+=1


In [13]:
print(doc_counts)

{'dog': 5, 'chase': 3, 'cat': 3, 'car': 3, 'tv': 2, 'watch': 1, 'sit': 1}


In [14]:
vocabulary = []
for doc in documents:
    for term in doc.split():
        if term not in vocabulary:
            vocabulary.append(term)
        

In [15]:
print(vocabulary)

['dog', 'chase', 'cat', 'car', 'tv', 'watch', 'sit']


In [16]:
print(set(vocabulary))

{'dog', 'car', 'chase', 'cat', 'tv', 'watch', 'sit'}


In [17]:
print(sorted(set(vocabulary)))

['car', 'cat', 'chase', 'dog', 'sit', 'tv', 'watch']


In [19]:
vocabulary_manual = sorted(set(vocabulary))

In [25]:
term_to_idx = {v:k for k,v in enumerate(vocabulary_manual)}

In [26]:
term_to_idx

{'car': 0, 'cat': 1, 'chase': 2, 'dog': 3, 'sit': 4, 'tv': 5, 'watch': 6}

In [27]:
V = len(vocabulary_manual)

In [29]:
tf_tdm_manual = np.zeros(shape=(V,N),dtype = np.int8)
print(tf_tdm_manual)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [30]:
for i in range (0,5):
    print(tf_tdm_manual[0][i])

0
0
0
0
0


In [33]:
for i,term in enumerate(vocabulary_manual):
    for j,doc in enumerate(documents):
        frequency=0
        for word in doc.split():
            if term==word:
                frequency+=1
        tf_tdm_manual[i][j]=frequency

In [34]:
print(tf_tdm_manual)

[[0 0 1 0 2]
 [1 2 0 0 0]
 [1 1 1 0 0]
 [2 0 0 2 1]
 [0 0 0 0 1]
 [0 0 1 1 0]
 [0 0 0 1 0]]


In [36]:
df = pd.DataFrame(tf_tdm_manual,index = list(vocabualry_manual),columns=['d{}'.format(c) for c in range (1,N+1)])

In [38]:
df

d1  d2  d3  d4  d5
car     0   0   1   0   2
cat     1   2   0   0   0
chase   1   1   1   0   0
dog     2   0   0   2   1
sit     0   0   0   0   1
tv      0   0   1   1   0
watch   0   0   0   1   0

In [41]:
count_vectorizer = CountVectorizer()
tf_tdm_sklearn = count_vectorizer.fit_transform(documents)
vocabulary_sklearn = count_vectorizer.get_feature_names_out()

In [42]:
print(vocabulary_sklearn)

['car' 'cat' 'chase' 'dog' 'sit' 'tv' 'watch']


In [51]:
df1 = pd.DataFrame(tf_tdm_sklearn.toarray().T,index = list(vocabulary_sklearn),columns=['d{}'.format(c) for c in range (1,N+1)])

In [52]:
df1

d1  d2  d3  d4  d5
car     0   0   1   0   2
cat     1   2   0   0   0
chase   1   1   1   0   0
dog     2   0   0   2   1
sit     0   0   0   0   1
tv      0   0   1   1   0
watch   0   0   0   1   0

In [53]:
tf_idf_manual = np.zeros(shape = (V,N),dtype= np.int8)

In [57]:
sdoc_counts = sorted(doc_counts)

In [60]:
for i,term in enumerate(vocabulary_manual):
    for j,doc in enumerate(documents):
        tf_idf_manual[i][j] = tf_tdm_manual[i][j]*doc_counts[term]

In [61]:
tf_idf_manual

array([[ 0,  0,  3,  0,  6],
       [ 3,  6,  0,  0,  0],
       [ 3,  3,  3,  0,  0],
       [10,  0,  0, 10,  5],
       [ 0,  0,  0,  0,  1],
       [ 0,  0,  2,  2,  0],
       [ 0,  0,  0,  1,  0]], dtype=int8)

In [62]:
df2 = pd.DataFrame(tf_idf_manual,index= list(vocabulary_manual),columns = ['d{}'.format(c) for c in range (1,N+1)])

In [63]:
df2

d1  d2  d3  d4  d5
car     0   0   3   0   6
cat     3   6   0   0   0
chase   3   3   3   0   0
dog    10   0   0  10   5
sit     0   0   0   0   1
tv      0   0   2   2   0
watch   0   0   0   1   0

In [64]:
tfidf_vectorizer = TfidfVectorizer(norm = None)


In [65]:
tf_idf_sklearn = tfidf_vectorizer.fit_transform(documents)
vocabulary_sklearn = tfidf_vectorizer.get_feature_names_out()

In [66]:
print(vocabulary_sklearn)

['car' 'cat' 'chase' 'dog' 'sit' 'tv' 'watch']


In [67]:
tf_idf_sklearn

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14 stored elements and shape (5, 7)>

In [68]:
df3 = pd.DataFrame(tf_idf_sklearn.toarray().T,index = list(vocabulary_manual),columns = ['d{}'.format(c) for c in range (1,N+1)])

In [69]:
df3

d1        d2        d3        d4        d5
car    0.000000  0.000000  1.693147  0.000000  3.386294
cat    1.693147  3.386294  0.000000  0.000000  0.000000
chase  1.405465  1.405465  1.405465  0.000000  0.000000
dog    2.810930  0.000000  0.000000  2.810930  1.405465
sit    0.000000  0.000000  0.000000  0.000000  2.098612
tv     0.000000  0.000000  1.693147  1.693147  0.000000
watch  0.000000  0.000000  0.000000  2.098612  0.000000

In [72]:
ngram_count_vectorizer = CountVectorizer(ngram_range=(1,2))
ngram_tf_model = ngram_count_vectorizer.fit_transform(documents)
ngram_vocabulary_manual = ngram_count_vectorizer.get_feature_names_out()

In [74]:
ngram_vocabulary_manual

array(['car', 'car chase', 'car sit', 'cat', 'cat chase', 'cat dog',
       'chase', 'chase cat', 'chase tv', 'dog', 'dog car', 'dog chase',
       'dog tv', 'dog watch', 'sit', 'sit car', 'tv', 'watch',
       'watch dog'], dtype=object)

In [78]:
df4 = pd.DataFrame(ngram_tf_model.toarray().T,index = list(ngram_vocabulary_manual),columns=['d{}'.format(c) for c in range (1,N+1)])

In [79]:
df4

d1  d2  d3  d4  d5
car         0   0   1   0   2
car chase   0   0   1   0   0
car sit     0   0   0   0   1
cat         1   2   0   0   0
cat chase   0   1   0   0   0
cat dog     1   0   0   0   0
chase       1   1   1   0   0
chase cat   1   1   0   0   0
chase tv    0   0   1   0   0
dog         2   0   0   2   1
dog car     0   0   0   0   1
dog chase   1   0   0   0   0
dog tv      0   0   0   1   0
dog watch   0   0   0   1   0
sit         0   0   0   0   1
sit car     0   0   0   0   1
tv          0   0   1   1   0
watch       0   0   0   1   0
watch dog   0   0   0   1   0